### ISSUE TITLE
How to know the profile name?

### ISSUE THREAD

**Issue by duxd2** [DMTF/Redfish-Profile-Simulator#11]
I do not know how to get the profile name and the details of resource and properties the profile defined?

**Comment by mraineri** [comment]
1/25: Ultimately it's up to the user to generate the profile (since this tool is used to take someone's profile and simulate an implementation). I think the name is a bit overloaded since the original incarnation of this tool was meant to simulate the OCP Profile, but in reality it doesn't consume a profile itself.

**Comment by duxd2** [comment]
Understood, thanks.
